/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as SignupRouteImport } from './app/routes/signup'
import { Route as PotStartRouteImport } from './app/routes/pot-start'
import { Route as PotCreateRouteImport } from './app/routes/pot-create'
import { Route as MyPageRouteImport } from './app/routes/my-page'
import { Route as MapGoogleRouteImport } from './app/routes/map-google'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as TravelAlbumIndexRouteImport } from './app/routes/travel-album.index'
import { Route as TravelAlbumRegionRouteImport } from './app/routes/travel-album.$region'
import { Route as MyPageProfileEditRouteImport } from './app/routes/my-page.profile-edit'
import { Route as LoginCallbackRouteImport } from './app/routes/login.callback'
import { Route as MyPagePotPotIdRouteImport } from './app/routes/my-page.pot.$potId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PotStartRoute = PotStartRouteImport.update({
  id: '/pot-start',
  path: '/pot-start',
  getParentRoute: () => rootRouteImport,
} as any)
const PotCreateRoute = PotCreateRouteImport.update({
  id: '/pot-create',
  path: '/pot-create',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPageRoute = MyPageRouteImport.update({
  id: '/my-page',
  path: '/my-page',
  getParentRoute: () => rootRouteImport,
} as any)
const MapGoogleRoute = MapGoogleRouteImport.update({
  id: '/map-google',
  path: '/map-google',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelAlbumIndexRoute = TravelAlbumIndexRouteImport.update({
  id: '/travel-album/',
  path: '/travel-album/',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelAlbumRegionRoute = TravelAlbumRegionRouteImport.update({
  id: '/travel-album/$region',
  path: '/travel-album/$region',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPageProfileEditRoute = MyPageProfileEditRouteImport.update({
  id: '/profile-edit',
  path: '/profile-edit',
  getParentRoute: () => MyPageRoute,
} as any)
const LoginCallbackRoute = LoginCallbackRouteImport.update({
  id: '/login/callback',
  path: '/login/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPagePotPotIdRoute = MyPagePotPotIdRouteImport.update({
  id: '/pot/$potId',
  path: '/pot/$potId',
  getParentRoute: () => MyPageRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map-google': typeof MapGoogleRoute
  '/my-page': typeof MyPageRouteWithChildren
  '/pot-create': typeof PotCreateRoute
  '/pot-start': typeof PotStartRoute
  '/signup': typeof SignupRoute
  '/login/callback': typeof LoginCallbackRoute
  '/my-page/profile-edit': typeof MyPageProfileEditRoute
  '/travel-album/$region': typeof TravelAlbumRegionRoute
  '/travel-album/': typeof TravelAlbumIndexRoute
  '/my-page/pot/$potId': typeof MyPagePotPotIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map-google': typeof MapGoogleRoute
  '/my-page': typeof MyPageRouteWithChildren
  '/pot-create': typeof PotCreateRoute
  '/pot-start': typeof PotStartRoute
  '/signup': typeof SignupRoute
  '/login/callback': typeof LoginCallbackRoute
  '/my-page/profile-edit': typeof MyPageProfileEditRoute
  '/travel-album/$region': typeof TravelAlbumRegionRoute
  '/travel-album': typeof TravelAlbumIndexRoute
  '/my-page/pot/$potId': typeof MyPagePotPotIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/map-google': typeof MapGoogleRoute
  '/my-page': typeof MyPageRouteWithChildren
  '/pot-create': typeof PotCreateRoute
  '/pot-start': typeof PotStartRoute
  '/signup': typeof SignupRoute
  '/login/callback': typeof LoginCallbackRoute
  '/my-page/profile-edit': typeof MyPageProfileEditRoute
  '/travel-album/$region': typeof TravelAlbumRegionRoute
  '/travel-album/': typeof TravelAlbumIndexRoute
  '/my-page/pot/$potId': typeof MyPagePotPotIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/map-google'
    | '/my-page'
    | '/pot-create'
    | '/pot-start'
    | '/signup'
    | '/login/callback'
    | '/my-page/profile-edit'
    | '/travel-album/$region'
    | '/travel-album/'
    | '/my-page/pot/$potId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/map-google'
    | '/my-page'
    | '/pot-create'
    | '/pot-start'
    | '/signup'
    | '/login/callback'
    | '/my-page/profile-edit'
    | '/travel-album/$region'
    | '/travel-album'
    | '/my-page/pot/$potId'
  id:
    | '__root__'
    | '/'
    | '/map-google'
    | '/my-page'
    | '/pot-create'
    | '/pot-start'
    | '/signup'
    | '/login/callback'
    | '/my-page/profile-edit'
    | '/travel-album/$region'
    | '/travel-album/'
    | '/my-page/pot/$potId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapGoogleRoute: typeof MapGoogleRoute
  MyPageRoute: typeof MyPageRouteWithChildren
  PotCreateRoute: typeof PotCreateRoute
  PotStartRoute: typeof PotStartRoute
  SignupRoute: typeof SignupRoute
  LoginCallbackRoute: typeof LoginCallbackRoute
  TravelAlbumRegionRoute: typeof TravelAlbumRegionRoute
  TravelAlbumIndexRoute: typeof TravelAlbumIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pot-start': {
      id: '/pot-start'
      path: '/pot-start'
      fullPath: '/pot-start'
      preLoaderRoute: typeof PotStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pot-create': {
      id: '/pot-create'
      path: '/pot-create'
      fullPath: '/pot-create'
      preLoaderRoute: typeof PotCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-page': {
      id: '/my-page'
      path: '/my-page'
      fullPath: '/my-page'
      preLoaderRoute: typeof MyPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map-google': {
      id: '/map-google'
      path: '/map-google'
      fullPath: '/map-google'
      preLoaderRoute: typeof MapGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel-album/': {
      id: '/travel-album/'
      path: '/travel-album'
      fullPath: '/travel-album/'
      preLoaderRoute: typeof TravelAlbumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel-album/$region': {
      id: '/travel-album/$region'
      path: '/travel-album/$region'
      fullPath: '/travel-album/$region'
      preLoaderRoute: typeof TravelAlbumRegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-page/profile-edit': {
      id: '/my-page/profile-edit'
      path: '/profile-edit'
      fullPath: '/my-page/profile-edit'
      preLoaderRoute: typeof MyPageProfileEditRouteImport
      parentRoute: typeof MyPageRoute
    }
    '/login/callback': {
      id: '/login/callback'
      path: '/login/callback'
      fullPath: '/login/callback'
      preLoaderRoute: typeof LoginCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-page/pot/$potId': {
      id: '/my-page/pot/$potId'
      path: '/pot/$potId'
      fullPath: '/my-page/pot/$potId'
      preLoaderRoute: typeof MyPagePotPotIdRouteImport
      parentRoute: typeof MyPageRoute
    }
  }
}

interface MyPageRouteChildren {
  MyPageProfileEditRoute: typeof MyPageProfileEditRoute
  MyPagePotPotIdRoute: typeof MyPagePotPotIdRoute
}

const MyPageRouteChildren: MyPageRouteChildren = {
  MyPageProfileEditRoute: MyPageProfileEditRoute,
  MyPagePotPotIdRoute: MyPagePotPotIdRoute,
}

const MyPageRouteWithChildren =
  MyPageRoute._addFileChildren(MyPageRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapGoogleRoute: MapGoogleRoute,
  MyPageRoute: MyPageRouteWithChildren,
  PotCreateRoute: PotCreateRoute,
  PotStartRoute: PotStartRoute,
  SignupRoute: SignupRoute,
  LoginCallbackRoute: LoginCallbackRoute,
  TravelAlbumRegionRoute: TravelAlbumRegionRoute,
  TravelAlbumIndexRoute: TravelAlbumIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './app/router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
